"""initial_schema

Revision ID: 5e52d15cf01f
Revises:
Create Date: 2026-07-08 22:10:43.228579
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5e52d15cf01f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('account_type', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('key', sa.String(), nullable=True),
        sa.Column('opening_balance', sa.Float(), nullable=True),
        sa.Column('is_system', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('currencies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('symbol', sa.String(), nullable=True),
        sa.Column('exchange_rate', sa.Float(), nullable=True),
        sa.Column('is_base', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('customers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('id_number', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('balance', sa.Float(), nullable=True),
        sa.Column('is_travel_agent', sa.Integer(), nullable=True),
        sa.Column('commission_pct', sa.Float(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('salary', sa.Float(), nullable=True),
        sa.Column('commission_rate', sa.Float(), nullable=True),
        sa.Column('advance_balance', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('services',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('suppliers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('balance', sa.Float(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('sys_config',
        sa.Column('k', sa.String(), nullable=False),
        sa.Column('v', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('k'),
    )
    op.create_table('treasury_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('balance', sa.Float(), nullable=True),
        sa.Column('currency_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('is_active', sa.Integer(), nullable=True),
        sa.Column('extra_permissions', sa.String(), nullable=True),
        sa.Column('revoked_permissions', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.create_table('attendances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_number', sa.String(), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('hotel_id', sa.Integer(), nullable=True),
        sa.Column('service_id', sa.Integer(), nullable=True),
        sa.Column('checkin', sa.Date(), nullable=True),
        sa.Column('checkout', sa.Date(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('paid_amount', sa.Float(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['hotel_id'], ['suppliers.id'], ),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contract_number', sa.String(), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('employee_withdrawals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('withdrawal_type', sa.String(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['treasury_accounts.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('hotels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('price_per_night', sa.Float(), nullable=True),
        sa.Column('available_rooms', sa.Integer(), nullable=True),
        sa.Column('supplier_id', sa.Integer(), nullable=True),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('contact_info', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('police_notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reservation_id', sa.Integer(), nullable=True),
        sa.Column('guest_name', sa.String(), nullable=True),
        sa.Column('passport_no', sa.String(), nullable=True),
        sa.Column('nationality', sa.String(), nullable=True),
        sa.Column('checkin_date', sa.Date(), nullable=True),
        sa.Column('checkout_date', sa.Date(), nullable=True),
        sa.Column('hotel_id', sa.Integer(), nullable=True),
        sa.Column('submitted', sa.Integer(), nullable=True),
        sa.Column('submitted_date', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
        sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('reservations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_number', sa.String(), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('guest_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('is_vip', sa.Integer(), nullable=True),
        sa.Column('special_requests', sa.Text(), nullable=True),
        sa.Column('reference_number', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('priority', sa.String(), nullable=True),
        sa.Column('internal_notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('checkin_date', sa.Date(), nullable=True),
        sa.Column('checkout_date', sa.Date(), nullable=True),
        sa.Column('passport_no', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('nationality', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('adults', sa.Integer(), nullable=True),
        sa.Column('children', sa.Integer(), nullable=True),
        sa.Column('children_ages', sa.String(), nullable=True),
        sa.Column('hotel_id', sa.Integer(), nullable=True),
        sa.Column('room_type', sa.String(), nullable=True),
        sa.Column('stay_type', sa.String(), nullable=True),
        sa.Column('meal_plan', sa.String(), nullable=True),
        sa.Column('room_count', sa.Integer(), nullable=True),
        sa.Column('extra_bed', sa.Integer(), nullable=True),
        sa.Column('checkin_time', sa.String(), nullable=True),
        sa.Column('checkout_time', sa.String(), nullable=True),
        sa.Column('stay_cost', sa.Float(), nullable=True),
        sa.Column('paid_to_hotel', sa.Float(), nullable=True),
        sa.Column('company_cost', sa.Float(), nullable=True),
        sa.Column('discount', sa.Float(), nullable=True),
        sa.Column('taxes', sa.Float(), nullable=True),
        sa.Column('paid_to_office', sa.Float(), nullable=True),
        sa.Column('transportation_cost', sa.Float(), nullable=True),
        sa.Column('excursions_cost', sa.Float(), nullable=True),
        sa.Column('visa_cost', sa.Float(), nullable=True),
        sa.Column('insurance_cost', sa.Float(), nullable=True),
        sa.Column('other_services_cost', sa.Float(), nullable=True),
        sa.Column('flight_number', sa.String(), nullable=True),
        sa.Column('pickup_time', sa.String(), nullable=True),
        sa.Column('dropoff_time', sa.String(), nullable=True),
        sa.Column('driver_name', sa.String(), nullable=True),
        sa.Column('guide_name', sa.String(), nullable=True),
        sa.Column('vehicle_info', sa.String(), nullable=True),
        sa.Column('ops_supplier_id', sa.Integer(), nullable=True),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.Column('reservation_rep_commission_type', sa.String(), nullable=True),
        sa.Column('reservation_rep_commission_value', sa.Float(), nullable=True),
        sa.Column('travel_agent_id', sa.Integer(), nullable=True),
        sa.Column('travel_agent_commission_type', sa.String(), nullable=True),
        sa.Column('travel_agent_commission_value', sa.Float(), nullable=True),
        sa.Column('sales_rep_id', sa.Integer(), nullable=True),
        sa.Column('sales_rep_commission_type', sa.String(), nullable=True),
        sa.Column('sales_rep_commission_value', sa.Float(), nullable=True),
        sa.Column('marketing_rep_id', sa.Integer(), nullable=True),
        sa.Column('marketing_rep_commission_type', sa.String(), nullable=True),
        sa.Column('marketing_rep_commission_value', sa.Float(), nullable=True),
        sa.Column('marketing_rep_commission_amount', sa.Float(), nullable=True),
        sa.Column('ops_supplier_commission_type', sa.String(), nullable=True),
        sa.Column('ops_supplier_commission_value', sa.Float(), nullable=True),
        sa.Column('ops_supplier_commission_amount', sa.Float(), nullable=True),
        sa.Column('employee_commission', sa.Float(), nullable=True),
        sa.Column('travel_agent_commission_amount', sa.Float(), nullable=True),
        sa.Column('sales_rep_commission_amount', sa.Float(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('vip_pass', sa.String(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
        sa.ForeignKeyConstraint(['marketing_rep_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['ops_supplier_id'], ['suppliers.id'], ),
        sa.ForeignKeyConstraint(['sales_rep_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['travel_agent_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('reservation_services',
        sa.Column('reservation_id', sa.Integer(), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
        sa.PrimaryKeyConstraint('reservation_id', 'service_id'),
    )
    op.create_table('tickets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ticket_number', sa.String(), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('airline', sa.String(), nullable=True),
        sa.Column('flight_no', sa.String(), nullable=True),
        sa.Column('departure', sa.String(), nullable=True),
        sa.Column('destination', sa.String(), nullable=True),
        sa.Column('departure_date', sa.DateTime(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('paid_amount', sa.Float(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('tourism_files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('file_type', sa.String(), nullable=True),
        sa.Column('file_path', sa.String(), nullable=True),
        sa.Column('upload_date', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('transports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('capacity', sa.Integer(), nullable=True),
        sa.Column('price_per_trip', sa.Float(), nullable=True),
        sa.Column('driver_name', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('treasury_transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['treasury_accounts.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('umrah_packages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('package_number', sa.String(), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('package_name', sa.String(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('paid_amount', sa.Float(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(), nullable=True),
        sa.Column('table_name', sa.String(), nullable=True),
        sa.Column('record_id', sa.Integer(), nullable=True),
        sa.Column('old_values', sa.Text(), nullable=True),
        sa.Column('new_values', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('collections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('collection_number', sa.String(), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('unallocated_amount', sa.Float(), nullable=True),
        sa.Column('allocated_amount', sa.Float(), nullable=True),
        sa.Column('payment_method', sa.String(), nullable=True),
        sa.Column('reference', sa.String(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('collection_allocations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('collection_id', sa.Integer(), nullable=True),
        sa.Column('reservation_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
        sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('reservation_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reservation_id', sa.Integer(), nullable=True),
        sa.Column('doc_type', sa.String(), nullable=True),
        sa.Column('file_path', sa.String(), nullable=True),
        sa.Column('upload_date', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('supplier_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('payment_number', sa.String(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('supplier_id', sa.Integer(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('allocated_amount', sa.Float(), nullable=True),
        sa.Column('unallocated_amount', sa.Float(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('supplier_payment_allocations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('payment_id', sa.Integer(), nullable=True),
        sa.Column('reservation_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['payment_id'], ['supplier_payments.id'], ),
        sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    op.drop_table('supplier_payment_allocations')
    op.drop_table('supplier_payments')
    op.drop_table('reservation_documents')
    op.drop_table('collection_allocations')
    op.drop_table('collections')
    op.drop_table('audit_logs')
    op.drop_table('umrah_packages')
    op.drop_table('treasury_transactions')
    op.drop_table('transports')
    op.drop_table('tourism_files')
    op.drop_table('tickets')
    op.drop_table('reservation_services')
    op.drop_table('reservations')
    op.drop_table('police_notifications')
    op.drop_table('hotels')
    op.drop_table('expenses')
    op.drop_table('employee_withdrawals')
    op.drop_table('contracts')
    op.drop_table('bookings')
    op.drop_table('attendances')
    op.drop_table('users')
    op.drop_table('treasury_accounts')
    op.drop_table('sys_config')
    op.drop_table('suppliers')
    op.drop_table('services')
    op.drop_table('employees')
    op.drop_table('customers')
    op.drop_table('currencies')
    op.drop_table('accounts')
